# Generated by Django 3.0.8 on 2020-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dataframe',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
