# Generated by Django 3.0.8 on 2020-11-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201106_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dataframe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
