# Generated by Django 3.0.8 on 2020-11-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201107_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='dataframe',
            new_name='data_table',
        ),
    ]
