# Generated by Django 3.0.8 on 2020-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20201107_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data_table',
            field=models.FileField(blank=True, null=True, upload_to='data_tables'),
        ),
    ]
